server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpiderPool?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root

  # redis????
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

jwt:
  secret: qweqqweqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
  expire: 8640000
